### ISSUE TITLE
FUSE streaming/seekable interface

### ISSUE THREAD

**Issue by dumblob** [ttsiodras/rsbep-backup#2]
If I'm not mistaken, the the current FUSE implementation doesn't support efficient seek in larger encoded files.

Would it be possible to implement it? I'd like to use it for videos, but they're huge and without "on demand" encoding/decoding it'll be difficult...

**Comment by ttsiodras** [comment]
The FUSE implementation was, to be honest, literally written as a "toy" - in a couple of hours on a boring Sunday afternoon. My only intent was to familiarize myself with the Python bindings of FUSE - it was never intended to be a *real* filesystem.

Basically, to efficiently use Reed-Solomon in a filesystem, one would need to design the filesystem around the limitations of RS. To my knowledge, no-one has done this. 

And as you rightfully noticed, my rsbep's interleaving (which is necessary for allowing RS to shield the data against bad sectors) implies that the data can only be accessed at the granularity of the shielded (~1M) blocks - making it completely unsuitable in its current form for anything beyond backups (for which, however, it fits perfectly). 

If you can afford to spend the effort to build something like that on top of RS, by all means do - but I for sure cannot. As I mention at the end of the README... "It works as is for me - if you don't like it, fork it and fix it to suit your needs".
