### ISSUE TITLE
32-bit assembler

### ISSUE THREAD

**Issue by b3taman** [ttsiodras/rsbep-backup#4]
Hi Thanassis,

After a series of disasters I am now implementing a rather serious backup system at home, but this project attracts me because of the ability to carry around important backups on a single device (no redundant _devices_ required).

The only warning from `./configure` I didn't manage to sort out is this one: `configure: WARNING: *** Can't use native x86 asm version... it will be slow...`

Although I haven't written in assembler for almost 30 years, I had a look and got the following:

```
$ gcc -c src/rs32asm.s
src/rs32asm.s: Assembler messages:
src/rs32asm.s:19: Error: invalid instruction suffix for `push'
src/rs32asm.s:22: Error: invalid instruction suffix for `push'
src/rs32asm.s:23: Error: invalid instruction suffix for `push'
src/rs32asm.s:24: Error: invalid instruction suffix for `push'
src/rs32asm.s:94: Error: invalid instruction suffix for `pop'
src/rs32asm.s:95: Error: invalid instruction suffix for `pop'
src/rs32asm.s:96: Error: invalid instruction suffix for `pop'
src/rs32asm.s:98: Error: invalid instruction suffix for `pop'
src/rs32asm.s:142: Error: invalid instruction suffix for `push'
src/rs32asm.s:144: Error: invalid instruction suffix for `push'
src/rs32asm.s:145: Error: invalid instruction suffix for `push'
src/rs32asm.s:146: Error: invalid instruction suffix for `push'
src/rs32asm.s:158: Error: invalid instruction suffix for `pop'
src/rs32asm.s:159: Error: invalid instruction suffix for `pop'
src/rs32asm.s:160: Error: invalid instruction suffix for `pop'
src/rs32asm.s:161: Error: invalid instruction suffix for `pop'
$ 
```

From what I found it seems the error is that the assembler is for a 32-bit environment (the file name and contents should have been a clue). Since these are becoming increasingly rare and I assume you are still using this, are you able to assist?

Ευχαριστώ εκ των προτέρων
John

**Comment by ttsiodras** [comment]
Hi John.

I am afraid I can't... Lack of time, for one - but more importantly, the code in question is not written by me. I simply reused the original sources, modifying them to cover my needs (as you can read [here](https://www.thanassis.space/rsbep.html#below) - look at the "Changeset from original rsbep" section). I have no insights into the assembly code or the algorithm in question - only it's operational semantics.

Of course I would more than welcome a PR - if anyone submits a working asm version for 64-bit environments.
As-is, the C version is (significantly) slower.

**Comment by marcizhu** [comment]
@b3taman I think you can compile 32-bit assembler if you add the `-m32` flag to GCC. This is a small & easy fix until someone makes a 64-bit assembler version of that code.

**Comment by ttsiodras** [comment]
@marcizhu: Are you saying that a 64-bit main program can call a 32-bit function?
Because sure, you can use `-m32` to compile a 32-bit object file - but when you try to link it with the rest (64-bit object files compiled from the C sources),  linking will fail - you can't mix and match different architectures in the same target binary:

    $ cat a.c
    #include <stdio.h>

    void foo()
    {
        puts("Hello.");
    }

    $ cat b.c
    extern void foo();

    int main()
    {
        foo();
    }

    $ gcc -c -m32 a.c

    $ gcc -c b.c

    $ file a.o b.o
    a.o: ELF 32-bit LSB relocatable, Intel 80386, version 1 (SYSV), not stripped
    b.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped

    $ gcc -o final a.o b.o
    /usr/bin/ld: i386 architecture of input file `a.o' is incompatible with i386:x86-64 output
    collect2: error: ld returned 1 exit status

**Comment by marcizhu** [comment]
No, all files must be compiled in 32-bit mode. Although it is possible for a 64-bit program to call a 32-bit function, that is not trivial and usually non-portable, aka it depends on the compiler & platform. My recomendation is to add `-m32` to all GCC calls.

**Comment by ttsiodras** [comment]
Ah, sure - that is easily done:

    CC="gcc -m32" ./configure
    make

But keep in mind, you are compiling a 32-bit binary then.

**Comment by ttsiodras** [comment]
@b3taman : Does the suggestion above cover your needs?

**Comment by b3taman** [comment]
Thanks for the ideas. Unfortunately it's a bit wobbly.

As per https://wiki.debian.org/Multiarch/HOWTO, I ran `dpkg --print-foreign-architectures`, which usefully returned `i386`, so there is hope on my system, at least.

I would appreciate some help; the last time I actually played around with this kind of thing was in the mid 1990s.

Looking at `config.log` revealed two lines in `configure` which mistakenly called gcc with `-V` instead of `-v`. After fixing those, this is what transpired.

```
$ CC="gcc -m32" ./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc -m32
checking for C compiler default output file name... 
configure: error: C compiler cannot create executables
See `config.log' for more details.
$ 
```

The relevant lines in config.log seem to be the following, which indicate that the 32-bit directive didn't quite pull through:

```
## ----------- ##
## Core tests. ##
## ----------- ##

configure:1797: checking build system type
configure:1815: result: x86_64-unknown-linux-gnu
configure:1837: checking host system type
configure:1852: result: x86_64-unknown-linux-gnu
configure:1874: checking target system type
configure:1889: result: x86_64-unknown-linux-gnu
configure:1933: checking for a BSD-compatible install
configure:1989: result: /usr/bin/install -c
configure:2000: checking whether build environment is sane
configure:2043: result: yes
configure:2071: checking for a thread-safe mkdir -p
configure:2110: result: /bin/mkdir -p
configure:2123: checking for gawk
configure:2139: found /usr/bin/gawk
configure:2150: result: gawk
configure:2161: checking whether make sets $(MAKE)
configure:2182: result: yes
configure:2419: checking for gcc
configure:2446: result: gcc -m32
configure:2684: checking for C compiler version
configure:2691: gcc -m32 --version >&5
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:2694: $? = 0
configure:2701: gcc -m32 -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) 
configure:2704: $? = 0
configure:2711: gcc -m32 -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) 
configure:2714: $? = 0
configure:2737: checking for C compiler default output file name
configure:2764: gcc -m32    conftest.c  >&5
/usr/bin/ld: cannot find Scrt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/6/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/6/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
collect2: error: ld returned 1 exit status
configure:2767: $? = 1
configure:2805: result: 
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME "rsbep"
| #define PACKAGE_TARNAME "rsbep"
| #define PACKAGE_VERSION "0.1.0-ttsiodras"
| #define PACKAGE_STRING "rsbep 0.1.0-ttsiodras"
| #define PACKAGE_BUGREPORT "ttsiodras@gmail.com"
| #define PACKAGE "rsbep"
| #define VERSION "0.1.0-ttsiodras"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:2812: error: C compiler cannot create executables
See `config.log' for more details.
```

Thanks again for the ideas. Looking into `configure` and trying to go up the rabbit hole soon showed me I need to defer to people who use this more than I do.

**Comment by ttsiodras** [comment]
I run Arch, where `CC="gcc -m32" ./configure` worked perfectly.

Are you sure you can build 32-bit binaries in your setup?
Try the simplest possible thing:

    $ echo "int main() { return 3; }" > test.c
    $ gcc -m32 test.c

Does this work?

**Comment by ttsiodras** [comment]
It's been a while since I lived in Debian - but if memory serves, I believe the output of `dpkg --print-foreign-architectures` means nothing unless you have also updated your `/etc/apt/sources.list` -  to something like this...

    $ cat /etc/apt/sources.list
    deb [arch=amd64,i386] https://deb.debian.org/debian buster main
    deb [arch=amd64,i386] http://security.debian.org/debian-security buster/updates main

That is, if you use Debian. If you use Ubuntu, adapt appropriately (basically prefix with the parts in brackets).
You must then `apt update` and `apt install gcc-multilib` .

**Comment by b3taman** [comment]
Ah, yes. Actually, no; the simple test didn't work.

Thank you for the pointer. I got it compiled by doing the following:
```
dpkg --add-architecture i386
apt update
apt install gcc-multilib
```
After that, it all worked. Thank you so much!

**Comment by ttsiodras** [comment]
Glad I could help!
Hope you find rsbep useful.
